[package]
name = "rust-crypto-lib-base"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
serde_json = "1.0.137"
starknet-crypto = "0.7.4"
lazy_static = "1.5.0"
