// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Slipstream.CommonDotNet.ExtendedSigner
{
    public static unsafe partial class ExtendedSigner
    {
        const string __DllName = "rust_crypto_lib_base";



        [DllImport(__DllName, EntryPoint = "starknet_sign", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern StarknetSign starknet_sign(byte* message, byte* private_key);

        [DllImport(__DllName, EntryPoint = "get_order_hash", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* get_order_hash(uint position_id, byte* base_asset_id_hex, long base_amount, byte* quote_asset_id_hex, long quote_amount, byte* fee_asset_id_hex, ulong fee_amount, ulong expiration, ulong salt, byte* user_public_key_hex, byte* domain_chain_id);

        [DllImport(__DllName, EntryPoint = "free_c_string_1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_c_string_1(byte* str1);

        [DllImport(__DllName, EntryPoint = "free_c_string_2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_c_string_2(byte* str1, byte* str2);

        [DllImport(__DllName, EntryPoint = "free_c_string_3", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_c_string_3(byte* str1, byte* str2, byte* str3);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct StarknetSign
    {
        public byte* r;
        public byte* s;
        public byte* v;
    }



}
